FROM centos:centos6

MAINTAINER James Cuzella &lt;james.cuzella@lyraphase.com&gt;

RUN yum update -y
RUN yum groupinstall -y "Development Tools"
RUN yum install -y libtool autoconf automake wget gettext which

