FROM ubuntu:16.04

MAINTAINER James Cuzella @trinitronx https://keybase.io/trinitronx/

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

RUN apt-get update
RUN apt-get install -y build-essential libtool libtool-bin automake pkg-config git wget gettext-base

