FROM ubuntu:12.04

MAINTAINER James Cuzella &lt;james.cuzella@lyraphase.com&gt;

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

RUN apt-get update
RUN apt-get install -y build-essential libtool automake pkg-config git wget

